[package]
name = "udp-blast"
version = "0.1.0"
authors = ["Mark Rechler"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
socket2 = { version = "0.4.0", features = ["all"] }
